### ISSUE TITLE
The issue of ‘Failed to fetch seqno 41319991’ which prevents block synchronization still exists

### ISSUE THREAD

**Issue by shenao78** [toncenter/ton-index-worker#88]
I previously mentioned this issue in [issue73](https://github.com/toncenter/ton-index-worker/issues/73), and you addressed it with a fix in [#74](https://github.com/toncenter/ton-index-worker/pull/74/files). However, after using that version, the problem still remains. I noticed that in [#76](https://github.com/toncenter/ton-index-worker/pull/76/files), the fix was removed again. Does the version in [#76](https://github.com/toncenter/ton-index-worker/pull/76/files) resolve this issue once more?

**Comment by dungeon-master-666** [comment]
There was an issue where `ton` submodule was accidentally rolled back (commit `803ceca`) and it was fixed in commit `8bd0932`. So there might be a chance that your code version is between these two commits. Please update to latest main branch.
We did not face that issue since then.

**Comment by aobalv123** [comment]
### I still have this problem

[ 3][t 3][2024-12-16 04:49:29.162866914][InsertManagerBase.cpp:81][!insertmanager]      Inserting batch[mb=1, b=5, txs=130, msgs=244, traces=100]
[ 3][t 7][2024-12-16 04:49:29.173951126][TraceAssembler.cpp:109][!trace_assembler]       Pending traces: 70398 Pending edges: 1652 Broken traces: 0
[ 3][t 2][2024-12-16 04:49:32.166191202][InsertManagerBase.cpp:81][!insertmanager]      Inserting batch[mb=1, b=5, txs=106, msgs=180, traces=73]
[ 3][t 2][2024-12-16 04:49:32.312162817][InsertManagerPostgres.cpp:1243][!insert_batch_postgres]        Indexed mintless jetton: 0:09F2E59DEC406AB26A5259A45D7FF23EF11F3E5C7C21DE0B0D2A1CBE52B76B3D
[ 3][t 5][2024-12-16 04:49:33.167313253][IndexScheduler.cpp:235][!indexscheduler]       42992619 / 42992621     0.365624/s (5s) Q[1M, 5b, 106t, 180m, 73T]
[ 1][t 1][2024-12-16 04:49:33.170902358][IndexScheduler.cpp:131][!indexquery]   Failed to fetch seqno 42992621: [Error : 651 : (0,2000000000000000,48035637): ltdb: block not found]
[ 2][t 1][2024-12-16 04:49:33.170942004][IndexScheduler.cpp:142][!indexscheduler]       Rescheduling seqno 42992621
[ 1][t 1][2024-12-16 04:49:34.173027462][IndexScheduler.cpp:131][!indexquery]   Failed to fetch seqno 42992621: [Error : 651 : (0,2000000000000000,48035637): ltdb: block not found]
[ 2][t 1][2024-12-16 04:49:34.173085217][IndexScheduler.cpp:142][!indexscheduler]       Rescheduling seqno 42992621
[ 1][t 6][2024-12-16 04:49:35.174220685][IndexScheduler.cpp:131][!indexquery]   Failed to fetch seqno 42992621: [Error : 651 : (0,6000000000000000,48052802): ltdb: block not found]
